version: "3.9"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "9999:5432"
  activemq:
    image: symptoma/activemq:latest
    environment:
      ACTIVEMQ_USERNAME: mq_user
      ACTIVEMQ_PASSWORD: mq_password
    ports:
      - "61616:61616"
      - "8161:8161"
